name: Tests

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: 18
  
    - name: Install
      run: npm ci

    - name: Test
      run: npm test
